######################################################################
# Automatically generated by qmake (2.01a) Mo Feb 16 09:30:52 2009
######################################################################

TEMPLATE = subdirs
CONFIG += ordered
SUBDIRS = qw_library qw_client qw_server qw_server_gui
