# #####################################################################
# Automatically generated by qmake (2.01a) Sa Feb 14 10:52:43 2009
# #####################################################################
TEMPLATE = app
HEADERS += ServerMonitorWindow.h \
    ServerMonitorController.h
SOURCES += ServerMonitorWindow.cpp \
    main.cpp \
    ServerMonitorController.cpp
FORMS += ServerMonitorWindow.ui

DESTDIR = ../bin
TARGET = qw_server_gui
